export type RNParallaxProps = {
    renderNavBar: Function,
    enderNavBar: Function,
    renderContent: Function,
    backgroundColor: string,
    backgroundImage: any,
    navbarColor: string,
    title: any,
    titleStyle: any,
    headerMaxHeight: number,
    headerMinHeight: number,
    scrollEventThrottle: number,
    extraScrollHeight: number,
    backgroundImageScale: number,
    contentContainerStyle: any,
    innerContainerStyle: any,
    scrollViewStyle: any,
    containerStyle: any,
    alwaysShowTitle: boolean,
    alwaysShowNavBar: boolean,
    statusBarColor: string,
    scrollViewProps: object,
  }
